// <auto-generated />
using System;
using ErdincBlog.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErdincBlog.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241016005157_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("75c0f7ba-1651-4e90-838b-3d37925e2d5b"),
                            ConcurrencyStamp = "6cbc2b02-d666-4d3a-8964-d99386a4b289",
                            Name = "Superadmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = new Guid("64649499-26bd-411c-a8a7-9d836c9d23ad"),
                            ConcurrencyStamp = "b7818261-c059-44df-8538-e5c3f556f1c0",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("d0a12845-4cd9-44b5-9f6a-e2d7bfb60687"),
                            ConcurrencyStamp = "181405b7-4169-4d10-9e55-05b3415e2846",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc61fa66-e621-4844-8219-945fd9da7867"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d1410045-03f5-407b-a91b-337754cc7eb6",
                            Email = "superadmin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Erdinç",
                            ImageId = new Guid("22a93f1f-652e-41fc-b9e4-b9b10fa75e2c"),
                            LastName = "Erdoğan",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGFuvWtD9svRHb23TVL4FvISDdvM03nsHV5zjDkRlvdYLIcrpPj7CJWMwW25wVeNlw==",
                            PhoneNumber = "+905359999999",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e5f4c26b-3f2f-4739-a984-dab0024fd41b",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("66bcf6c7-945a-43a5-9027-447f315c66c0"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30084869-dd7a-4de7-8393-9af90a3749fe",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            ImageId = new Guid("6b5909d6-0381-40ec-964f-06571a6af36a"),
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEM4xgox/QPVg1IWirFLE++oDYVtxhzlG3P74mKln/ENz7sBkmknNdHT7zNn4pXD4GA==",
                            PhoneNumber = "+905359999988",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "94ad3410-cf82-4b60-bfca-04db1ace60a8",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("dc61fa66-e621-4844-8219-945fd9da7867"),
                            RoleId = new Guid("75c0f7ba-1651-4e90-838b-3d37925e2d5b")
                        },
                        new
                        {
                            UserId = new Guid("66bcf6c7-945a-43a5-9027-447f315c66c0"),
                            RoleId = new Guid("64649499-26bd-411c-a8a7-9d836c9d23ad")
                        });
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d6d9edc-9804-4c7f-8f7a-f3709cdaabd7"),
                            CategoryId = new Guid("8020b791-c3d3-406a-95e0-4834ca3d24d2"),
                            Content = "Entity Nasıl Oluşturulur? Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur justo mauris, aliquet ultrices vestibulum vitae, lacinia vitae lectus. Duis ac placerat diam. Suspendisse cursus porta arcu, eu consequat lectus posuere ut. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla urna felis, venenatis quis mauris sed, suscipit pretium orci. Nullam pretium lectus diam, eget dignissim orci volutpat sit amet. Nullam sed iaculis justo, tempus viverra nunc. In lorem tortor, accumsan vitae quam vitae, condimentum varius ex. Morbi porttitor orci eu suscipit tincidunt. Ut facilisis pulvinar leo ac consequat. Nulla sit amet felis elementum, condimentum ligula at, ultrices orci. Sed quis efficitur felis. Vivamus rutrum mi sit amet diam viverra aliquet. Curabitur tempor lacus justo, gravida egestas metus viverra dictum. Morbi suscipit nulla ut eleifend vestibulum.",
                            CreatedBy = "Erdinç Erdoğan",
                            CreatedDate = new DateTime(2024, 10, 16, 3, 51, 57, 357, DateTimeKind.Local).AddTicks(7522),
                            ImageId = new Guid("22a93f1f-652e-41fc-b9e4-b9b10fa75e2c"),
                            IsDeleted = false,
                            Title = "ASP.NET CORE MVC - Entity Nasıl Oluşturulur?",
                            UserId = new Guid("dc61fa66-e621-4844-8219-945fd9da7867"),
                            ViewCount = 61
                        },
                        new
                        {
                            Id = new Guid("2046ba9e-f938-4e36-be9c-562bc4822ae0"),
                            CategoryId = new Guid("2b7b786b-f828-4ee7-b0e7-18dd93e7b0c6"),
                            Content = "C# - Döngüler Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur justo mauris, aliquet ultrices vestibulum vitae, lacinia vitae lectus. Duis ac placerat diam. Suspendisse cursus porta arcu, eu consequat lectus posuere ut. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla urna felis, venenatis quis mauris sed, suscipit pretium orci. Nullam pretium lectus diam, eget dignissim orci volutpat sit amet. Nullam sed iaculis justo, tempus viverra nunc. In lorem tortor, accumsan vitae quam vitae, condimentum varius ex. Morbi porttitor orci eu suscipit tincidunt. Ut facilisis pulvinar leo ac consequat. Nulla sit amet felis elementum, condimentum ligula at, ultrices orci. Sed quis efficitur felis. Vivamus rutrum mi sit amet diam viverra aliquet. Curabitur tempor lacus justo, gravida egestas metus viverra dictum. Morbi suscipit nulla ut eleifend vestibulum.",
                            CreatedBy = "Erdinç Erdoğan",
                            CreatedDate = new DateTime(2024, 10, 16, 3, 51, 57, 357, DateTimeKind.Local).AddTicks(7528),
                            ImageId = new Guid("6b5909d6-0381-40ec-964f-06571a6af36a"),
                            IsDeleted = false,
                            Title = "C# - Döngüler",
                            UserId = new Guid("66bcf6c7-945a-43a5-9027-447f315c66c0"),
                            ViewCount = 61
                        });
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8020b791-c3d3-406a-95e0-4834ca3d24d2"),
                            CreatedBy = "Erdinç Erdoğan",
                            CreatedDate = new DateTime(2024, 10, 16, 3, 51, 57, 357, DateTimeKind.Local).AddTicks(7733),
                            IsDeleted = false,
                            Name = "ASP.NET CORE MVC"
                        },
                        new
                        {
                            Id = new Guid("2b7b786b-f828-4ee7-b0e7-18dd93e7b0c6"),
                            CreatedBy = "Erdinç Erdoğan",
                            CreatedDate = new DateTime(2024, 10, 16, 3, 51, 57, 357, DateTimeKind.Local).AddTicks(7736),
                            IsDeleted = false,
                            Name = "C#"
                        });
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22a93f1f-652e-41fc-b9e4-b9b10fa75e2c"),
                            CreatedBy = "Erdinç Erdoğan",
                            CreatedDate = new DateTime(2024, 10, 16, 3, 51, 57, 357, DateTimeKind.Local).AddTicks(7863),
                            FileName = "img/ornek",
                            FileType = "jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("6b5909d6-0381-40ec-964f-06571a6af36a"),
                            CreatedBy = "Erdinç Erdoğan",
                            CreatedDate = new DateTime(2024, 10, 16, 3, 51, 57, 357, DateTimeKind.Local).AddTicks(7867),
                            FileName = "img/c-sharp-test",
                            FileType = "png",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppRoleClaim", b =>
                {
                    b.HasOne("ErdincBlog.Entity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppUser", b =>
                {
                    b.HasOne("ErdincBlog.Entity.Entities.Image", "Image")
                        .WithMany("Users")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppUserClaim", b =>
                {
                    b.HasOne("ErdincBlog.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppUserLogin", b =>
                {
                    b.HasOne("ErdincBlog.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppUserRole", b =>
                {
                    b.HasOne("ErdincBlog.Entity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErdincBlog.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppUserToken", b =>
                {
                    b.HasOne("ErdincBlog.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.Article", b =>
                {
                    b.HasOne("ErdincBlog.Entity.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErdincBlog.Entity.Entities.Image", "Image")
                        .WithMany("Articles")
                        .HasForeignKey("ImageId");

                    b.HasOne("ErdincBlog.Entity.Entities.AppUser", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Image");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.AppUser", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("ErdincBlog.Entity.Entities.Image", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
